### ISSUE TITLE
How to extend django_bootstrap5 default templates

### ISSUE THREAD

**Issue by qodrinzo** [zostera/django-bootstrap5#129]
As a user of Conda environments on Windows 10, 

I want to extend `C:\Users\Test\Programming\anaconda3\envs\Django\lib\site-packages\django_bootstrap5\src\django_bootstrap5\templates\django_bootstrap5\bootstrap5.html` 

by a template inside some app of my Django project; eg `C:\Users\Test\Programming\team\project\app\templates\app\base.html`.

How can I do it?

> Exception Type: NoReverseMatch
> Exception Value: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
> Exception Location: C:\Users\Test\Programming\anaconda3\envs\Django\lib\site-packages\django\urls\resolvers.py, line 694, in _reverse_with_prefix
> Error during template rendering
> In template C:\Users\Test\Programming\anaconda3\envs\Django\lib\site-packages\django_bootstrap5\templates\django_bootstrap5\bootstrap5.html, error at line 11

**Comment by dyve** [comment]
Hi, it looks like you might need some help getting set up.

- The error you are seeing is because the url name "home" is not found in your Django url config. See https://docs.djangoproject.com/en/3.2/topics/http/urls/
- Template inheritance is explained here https://docs.djangoproject.com/en/3.2/ref/templates/language/#template-inheritance

Both of these are not issues in this package, so I will close this ticket.

The best place to ask for help with issues like these is [StackOverflow](https://stackoverflow.com). You will receive answers from a community of programmers!

If you ask your question on StackOverflow and use the tag `django-bootstrap5`, we'll be happy to reply over there!
