### ISSUE TITLE
DateField not rendered as a Date input

### ISSUE THREAD

**Issue by pep-un** [zostera/django-bootstrap5#445]
Hello,

the Django `DateField` is currently rendered as an input `type="texte" `and not as an `input type="date"`. 
[Mozilla documentation on input date](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/date)

It would be a nice improvement to render date with this type of input to have a date picker on the form.

Regards

**Comment by Actionb** [comment]
Looks like this might be an issue on Django's side.
The `input_type` attribute of the `DateInput` widget is set to `text` instead of `date`, so a bound date formfield renders like this:  `'<input type="text" name="field" required id="id_field">'`. 

You can specify the input type when declaring the widget: `widget = forms.DateInput(attrs={"type": "date"})`

**Comment by dyve** [comment]
That's correct, we follow Django's lead here.
